---
# Homepage configuration
# See https://fontawesome.com/search for icons options
# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml
title: "Admin Portal"
subtitle: "pknw1"
# documentTitle: "Welcome" # Customize the browser tab text
logo: "https://www.pknw1.co.uk/assets/images/logo-stacked-511x282.png"
header: true # Set to false to hide the header
footer: 'pknw1'
columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: dark 
theme: default # 'default' or one of the themes available in 'src/assets/themes'.
# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "/assets/your/light/bg.png" # prefix with your sub subpath if any (ex: /homer/assets/...)
  dark:
    highlight-primary: "#232323"
    highlight-secondary: "#e5a00d"
    highlight-hover: "#232323"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#e5a00d"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#e5a00d"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "/assets/your/dark/bg.png" # prefix with your sub subpath if any (ex: /homer/assets/...)
# Optional message
message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  #
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  # url: https://api.chucknorris.io/jokes/random
  # mapping:
  #   title: 'id'
  #   content: 'value'
  # refreshInterval: 10000
  #style: "is-error"
  #title: "Optional message!"
  #icon: "fa fa-exclamation-triangle"
  # The content also accepts HTML content, so you can add divs, images or whatever you want to make match your needs.
  #content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Admin Console"
    icon: "fa-solid fa-sliders"
    url: "https://admin.pknw1.co.uk"
  - name: pknw1.co.uk
    icon: "fab fa-github"
    url: "https://www.pknw1.co.uk"
    target: "_blank" # optional html tag target attribute
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/pknw1"
    target: "_blank" # optional html tag target attribute
#  - name: "DockerHub"
#    icon: "fa-brands fa-docker"
#    url: "https://hub.docker.com/u/pknw1"
#  - name: "VPS"
#    icon: "fa-brands fa-docker"
#    url: "https://homer.vps.pknw1.co.uk"
#  - name: "Users Dash"
#    icon: "fa-brands fa-docker"
#    url: "https://dashboard.pknw1.co.uk"
  # this will link to a second homer page that will load config from page2.yml and keep default config values as in config.yml file
  # see url field and assets/page.yml used in this example:
  - name: "Services"
    icon: "fas fa-file-alt"
    url: "#page2"
services:
  - name: Server Apps
    icon: "fas fa-code-branch"
    items:
      - name: "Plex"
        logo: "https://cdn.freebiesupply.com/logos/large/2x/plex-logo-png-transparent.png"
        url: "https://app.plex.tv/desktop"
        target: "_blank"
      - name: "Webmin"
        logo: "https://www.unixmen.com/wp-content/uploads/2017/07/webmin-logo.png"
        url: "https://webmin.admin.pknw1.co.uk"
        target: "_blank"
      - name: "Dockge"
        logo: "https://static-00.iconduck.com/assets.00/portainer-icon-1465x2048-t155ekm0.png"
        url: "https://dockge.admin.pknw1.co.uk"
        target: "_blank"
      - name: "OVH"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Logo-OVH.svg/1280px-Logo-OVH.svg.png"
        url: "https://www.ovh.com/manager"
        target: "_blank"
      - name: System
        icon: "fa-solid fa-heart-pulse"
        url: http://glances:61208
        type: Glances
        stats: [cpu, mem] # Metric to display. Possible values are: load, cpu, mem, swap.
        updateInterval: 5000 # (Optional) Interval (in ms) for updating the stats   
      - name: "qBittorrent"
        logo: "assets/tools/sample.png"
        url: "https://utorrent.admin.pknw1.co.uk" # Your rTorrent web UI, f.e. ruTorrent or Flood.
        type: "qBittorrent"
        rateInterval: 2000 # Interval for updating the download and upload rates.
        torrentInterval: 5000 # Interval for updating the torrent count.
        target: "_blank" # optional html a tag target attribute
  - name: Content
    icon: "fas fa-code-branch"
    items:
      - name: "homer"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://raw.githubusercontent.com/bastienwirtz/homer/main/public/logo.png"
        #tag: "Content"
        url: "https://admin.pknw1.co.uk"
        target: "_blank"  
      - name: "download"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://cdn3.iconfinder.com/data/icons/pyconic-icons-1-2/512/download-2-1024.png"
        #tag: "Content"
        url: "https://download.pknw1.co.uk"
        target: "_blank"  
      - name: "utorrent"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://iconape.com/wp-content/files/zo/346429/png/346429.png"
        #tag: "Content"
        url: "https://ut.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "flaresolverr"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://avatars.githubusercontent.com/u/75936191?s=400&v=4"
        #tag: "Content"
        url: "https://flaresolverr.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "caddy"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://www.redpill-linpro.com/techblog/images/posts/caddy2-logo.png"
        #tag: "Content"
        url: "https://dev-www.pknw1.co.uk"
        target: "_blank"  
      - name: "caddy-www"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://www.pknw1.co.uk/assets/images/icon-128x77.png"
        #tag: "Content"
        url: "https://www.pknw1.co.uk"
        target: "_blank"  
  - name: Core
    icon: "fas fa-code-branch"
    items:
      - name: "proxymanager"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://nginxproxymanager.com/icon.png"
        #tag: "Core"
        url: "https://proxymanager.admin.pknw1.co.uk"
        target: "_blank"  
  - name: Monitoring
    icon: "fas fa-code-branch"
    items:
      - name: "glances"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://nicolargo.github.io/glances/public/images/glances.png"
        #tag: "Monitoring"
        url: "https://glances.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "uptime"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://strawberrysec.net/assets/images/HomeLab/Uptime_Kuma_Header.png"
        #tag: "Monitoring"
        url: "https://status.pknw1.co.uk"
        target: "_blank"  
  - name: Requests
    icon: "fas fa-code-branch"
    items:
      - name: "prowlarr"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://static-00.iconduck.com/assets.00/prowlarr-icon-2048x2048-2pxvehfe.png"
        #tag: "Requests"
        url: "https://prowlarr.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "radarr"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://static-00.iconduck.com/assets.00/radarr-icon-231x256-t45eodqo.png"
        #tag: "Requests"
        url: "https://radarr.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "metube-tailscale"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://static-00.iconduck.com/assets.00/metube-icon-231x256-t45eodqo.png"
        #tag: "Requests"
        url: "https://metube.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "sonarr"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://res.cloudinary.com/razordarkamg/image/upload/v1621212884/SonarrV3_pufacd.png"
        #tag: "Requests"
        url: "https://sonarr.admin.pknw1.co.uk"
        target: "_blank"  
  - name: Utilities
    icon: "fas fa-code-branch"
    items:
      - name: "dozzle"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://linuxiac.b-cdn.net/wp-content/uploads/2024/02/dozzle.jpg"
        #tag: "Utilities"
        url: "https://dozzle.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "piholeb"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://www.mycyberuniverse.com/images/articles/Arthur/how-update-pi-hole/pi-hole-logo.png"
        #tag: "Utilities"
        url: "https://pihole.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "squid"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://kifarunix.com/wp-content/uploads/2018/12/squid-proxy.png"
        #tag: "Utilities"
        url: "https://squid.admin.pknw1.co.uk"
        target: "_blank"  
      - name: "portainer"
        #subtitle: "Launch WebApp in a new tab"
        logo: "https://linuxiac.b-cdn.net/wp-content/uploads/2024/02/dozzle.jpg"
        #tag: "Utilities"
        url: "https://portainer.admin.pknw1.co.uk"
        target: "_blank"  
